### ISSUE TITLE
Wrong Link to the Food4Rhino website

### ISSUE THREAD

**Issue by zohozer** [interopxyz/PdfPlus#3]
The correct link to this components into the Food4Rhino website should be:

`https://www.food4rhino.com/en/app/pdf`
instead of:
`https://www.food4rhino.com/en/app/pdf-plus`

The actual URL gives this error:
`Sorry, the page you requested was not found.`

**Comment by interopxyz** [comment]
Thank you for the catch. 
The project names were all recently changed on Food4Rhino and, apparently, this broke the links as well.
