### ISSUE TITLE
Downloadable components?

### ISSUE THREAD

**Issue by zohozer** [interopxyz/PdfPlus#4]
I am using Rhino6 and want to use this components, however I can't install plugins or components from URLs like the ones that are posted in the Food4Rhino website.

It is possible to create binary files that are zipped and create a link for that archives?

Best regards.

**Comment by interopxyz** [comment]
I'll only be posting the downloads on Food4Rhino.
You can use the package manager in Rhino to install them.
Then access the .gha and .dll in the package manager folder.

**Comment by zohozer** [comment]
The problem it is that the package manager seems to be broke in Rhino6. I can't install any packages from URLs. Some developers are putting both URLs and also downloadable .zip files with their components.
